-- Runbook step 17: the platform's monthly commission invoice to each seller.
--
-- Two nullable columns and their unique indexes. Postgres treats NULLs as distinct under a unique
-- index, so all 374 existing invoices and every existing customer coexist without a backfill.
--
-- Invoice.commissionPeriodKey holds "<sellerId>:<YYYY-MM>" on a COMMISSION invoice and NULL on
-- every other. ⚠️ The uniqueness is its only job: the invoice is generated by a route the owner
-- presses, and pressing it twice for one month would charge a seller twice for the same service
-- and put two documents in one filed GSTR-1. Composite because neither half is unique alone — a
-- seller has many months and a month has many sellers.
--
-- Customer.sellerAccountId is the handle that keeps a seller's BUSINESS identity apart from the
-- personal shopping account that may share their phone number. ⚠️ Resolving a seller's billing
-- customer by phone, the way app users are resolved, would merge the two: the same person, and
-- emphatically not the same taxable entity.
ALTER TABLE "Customer" ADD COLUMN     "sellerAccountId" TEXT;
ALTER TABLE "Invoice" ADD COLUMN     "commissionPeriodKey" TEXT;

CREATE UNIQUE INDEX "Customer_sellerAccountId_key" ON "Customer"("sellerAccountId");
CREATE UNIQUE INDEX "Invoice_commissionPeriodKey_key" ON "Invoice"("commissionPeriodKey");
